DROP TABLE IF EXISTS PRODUCTOS;

CREATE TABLE PRODUCTOS(ID INT AUTO_INCREMENT PRIMARY KEY, CODIGO INT NOT NULL, NOMBRE VARCHAR(50) NOT NULL, DESCRIPCION VARCHAR(300) NOT NULL, PRECIO DOUBLE NOT NULL, DIRECCION VARCHAR(100) NOT NULL);

//terminar parte de los cruces en tablas
